# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: false

# Setup
title:            'CAT blog'
tagline:          'Computed Tomography'
description:      'Scribblings about my many hours spent tinkering with CT reconstruction algorithms. Made by <a href="https://twitter.com/alexuk86" target="_blank">@AlexUK86</a>.'
url:              https://alexuk86.github.io/
baseurl:          https://alexuk86.github.io/

author:
  name:           'Alex Beardmore'
  url:            https://twitter.com/alexuk86

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
  

#my changes

excerpt_separator: <!--more-->  
